FROM node:4.5.0
MAINTAINER Max Kimambo <max.kimambo@klab-berlin.com>

ARG GITHUB_KEY=github.key
ENV NODE_ENV=Production

RUN mkdir -p /var/opt/pizzaMargherita
WORKDIR /var/opt/pizzaMargherita

#Add git key to checkout code
ADD $GITHUB_KEY /root/.ssh/id_rsa
RUN chmod 700 /root/.ssh/id_rsa

RUN echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config

ADD package.json /var/opt/pizzaMargherita
COPY . /var/opt/pizzaMargherita

RUN npm install

ENTRYPOINT ["node", "index.js"]
